### ISSUE TITLE
Adding globalization to another model

### ISSUE THREAD

**Issue by bosskovic** [solidusio-contrib/solidus_globalize#12]
Hi there, and thanks for a great gem!

I need some help adding globalization to another model. I added this code to the model decorator and migration:

```
module Spree
  Page.class_eval do
    translates :title, :slug, :body, :meta_title, :meta_description, :meta_keywords,
               fallbacks_for_empty_translations: true
    include SolidusGlobalize::Translatable
  end
end
```

```
class AddTranslationsToPage < ActiveRecord::Migration
  def up
    unless table_exists?(:spree_page_translations)
      params = { title: :string, slug: :string, body: :text, meta_title: :string, meta_description: :text, meta_keywords: :text }
      Spree::Page.create_translation_table!(params, { migrate_data: true })
    end
  end

  def down
    Spree::Page.drop_translation_table! migrate_data: true
  end
end
```

When I run the migration, this is what I get:

```
$ rake db:migrate
rake aborted!
NoMethodError: undefined method `whitelisted_ransackable_associations' for #<Class:0x0000000b04c8f0>
/home/m/.rvm/gems/ruby-2.3.0@viniditerroir_solidus/gems/activerecord-4.2.6/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/home/m/.rvm/gems/ruby-2.3.0@viniditerroir_solidus/bundler/gems/solidus_globalize-02ed2c1d3937/app/models/concerns/solidus_globalize/translatable.rb:7:in `block in <module:Translatable>'
/home/m/.rvm/gems/ruby-2.3.0@viniditerroir_solidus/gems/activesupport-4.2.6/lib/active_support/concern.rb:120:in `class_eval'
...
```

If I move `include SolidusGlobalize::Translatable` above the `translates ...` call, I get a different message when running the migration:

```
$ rake db:migrate
rake aborted!
ArgumentError: No association found for name `translations'. Has it been defined yet?
/home/m/.rvm/gems/ruby-2.3.0@viniditerroir_solidus/gems/activerecord-4.2.6/lib/active_record/nested_attributes.rb:319:in `block in accepts_nested_attributes_for'
/home/m/.rvm/gems/ruby-2.3.0@viniditerroir_solidus/gems/activerecord-4.2.6/lib/active_record/nested_attributes.rb:307:in `each'
/home/m/.rvm/gems/ruby-2.3.0@viniditerroir_solidus/gems/activerecord-4.2.6/lib/active_record/nested_attributes.rb:307:in `accepts_nested_attributes_for'
/home/m/.rvm/gems/ruby-2.3.0@viniditerroir_solidus/bundler/gems/solidus_globalize-02ed2c1d3937/app/models/concerns/solidus_globalize/translatable.rb:6:in `block in <module:Translatable>'
/home/m/.rvm/gems/ruby-2.3.0@viniditerroir_solidus/gems/activesupport-4.2.6/lib/active_support/concern.rb:120:in `class_eval'
```

which is kind of expected. What am I missing?
Let me just add that I successfully added solidus_globalize and run all of its migrations.

**Comment by bosskovic** [comment]
I "solved" this by adding the contents of the `SolidusGlobalize::Translatable` concern directly to the decorator and omitting `klass.whitelisted_ransackable_associations`, and now I can successfully update the translations. What are these "whitelisted_ransackable_associations" for and will this pose a problem for me in future?

**Comment by bosskovic** [comment]
ok, I figured it out. The model that I am adding globalize to does not descend from Spree::Base, so the solution is to add Spree::RansackableAttributes concern to it in the decorator.
