### ISSUE TITLE
Unable to run generator after installation. 

### ISSUE THREAD

**Issue by AndreiMotinga** [solidusio-contrib/solidus_globalize#29]
#### error
```
/usr/local/lib/ruby/gems/2.3.0/bundler/gems/solidus_globalize-1538996926f2/app/models/spree/store_decorator.rb:3:in `block in <module:Spree>': undefined method `translates' for Store:Module (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/solidus_globalize-1538996926f2/app/models/spree/store_decorator.rb:2:in `class_eval'
	from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/solidus_globalize-1538996926f2/app/models/spree/store_decorator.rb:2:in `<module:Spree>'
	from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/solidus_globalize-1538996926f2/app/models/spree/store_decorator.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/solidus_globalize-1538996926f2/lib/solidus_globalize/engine.rb:27:in `block in activate'
	from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/solidus_globalize-1538996926f2/lib/solidus_globalize/engine.rb:26:in `glob'
	from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/solidus_globalize-1538996926f2/lib/solidus_globalize/engine.rb:26:in `activate'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:396:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:396:in `block in make_lambda'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:546:in `catch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:546:in `block in default_terminator'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:170:in `block in halting'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:454:in `block in call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:454:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:454:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_prepare_callbacks'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/reloader.rb:87:in `prepare!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /Users/andrei/dev/am-solidus-default-store/config/environment.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

#### gemfile
```
source "https://rubygems.org"

ruby "2.3.1"

gem "autoprefixer-rails"
# gem "delayed_job_active_record"
gem "flutie"
gem "jquery-rails"
gem "pg"
gem "puma"
gem "rack-canonical-host"
gem "rails", "~> 5.0.2"
gem "recipient_interceptor"
gem "sass-rails", "~> 5.0"
gem "sprockets", ">= 3.0.0"
gem "uglifier"
gem "turbolinks"

gem "aws-sdk"

gem "solidus", "~> 2.2.0.rc1"
gem "solidus_auth_devise"
gem 'solidus_i18n', github: 'solidusio-contrib/solidus_i18n', branch: 'master'
gem 'globalize', github: 'globalize/globalize'
gem 'solidus_globalize', github: 'AndreiMotinga/solidus_globalize'

group :development do
  gem "spring"
  gem "spring-commands-rspec"
  gem "web-console"
end

group :development, :test do
  gem "awesome_print"
  gem "bullet"
  gem "bundler-audit", ">= 0.5.0", require: false
  gem "dotenv-rails"
  gem "factory_girl_rails"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rspec-rails", "~> 3.5.0.beta4"
end

group :development, :staging do
  gem "rack-mini-profiler", require: false
end

group :test do
  gem "capybara-webkit"
  gem "database_cleaner"
  gem "formulaic"
  gem "launchy"
  gem "shoulda-matchers"
  gem "simplecov", require: false
  gem "timecop"
  gem "webmock"
end

group :staging, :production do
  gem "rack-timeout"
  gem "rails_stdout_logging"
end

```

**Comment by AndreiMotinga** [comment]
fun note, I've created my app with the name  `store`... world came crashing.
